### ISSUE TITLE
Just errors in the logs

### ISSUE THREAD

**Issue by geedsen** [fsaris/home-assistant-zonneplan-one#122]
Logger: homeassistant.helpers.typing
Source: helpers/deprecation.py:197
First occurred: June 11, 2024 at 9:19:13 PM (8 occurrences)
Last logged: June 11, 2024 at 9:19:22 PM

HomeAssistantType was used from zonneplan_one, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'zonneplan_one' custom integration

And this one:

024-06-11 21:19:13.867 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'zonneplan_one' at custom_components/zonneplan_one/zonneplan_api/api.py, line 32: f = open(script_directory + '/../manifest.json') (offender: /config/custom_components/zonneplan_one/zonneplan_api/api.py, line 32: f = open(script_directory + '/../manifest.json')), please create a bug report at https://github.com/fsaris/home-assistant-zonneplan-one/issues
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
await self.async_setup(hass, integration=integration)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/zonneplan_one/__init__.py", line 46, in async_setup_entry
zonneplanApi = api.AsyncConfigEntryAuth(
File "/config/custom_components/zonneplan_one/api.py", line 22, in __init__
super().__init__(websession)
File "/config/custom_components/zonneplan_one/zonneplan_api/api.py", line 26, in __init__
"x-ha-integration": self._get_integration_version(),
File "/config/custom_components/zonneplan_one/zonneplan_api/api.py", line 32, in _get_integration_version
f = open(script_directory + '/../manifest.json')

**Comment by pietje63** [comment]
Same here

**Comment by deqw** [comment]
Rollback HA core version: `ha core update --version=2024.5.5` and wait for an update that solves this loop.

**Comment by fsaris** [comment]
You can install main version it's fixed there.

It's also a warning, so you can just use it

**Comment by fsaris** [comment]
Fixed in release https://github.com/fsaris/home-assistant-zonneplan-one/releases/tag/2024.6.0
