### ISSUE TITLE
Errors from Zonneplan-One integration

### ISSUE THREAD

**Issue by dajomas** [fsaris/home-assistant-zonneplan-one#34]
Since Nov 30, the Zonneplan integration (0.0.10) returns an error when connecting to the Zonneplan API:
```ERROR (MainThread) [custom_components.zonneplan_one.coordinator] Error requesting zonneplan_one data: 403, message='Forbidden', url=URL('https://app-api.zonneplan.nl/connections/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/summary')```

After upgrading to version 0.0.14 (hoping the connection issue is solved) I get the following error:
```
ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.zonneplan_one.sensor
Traceback (most recent call last):
  File "/srv/hass11/lib/python3.9/site-packages/homeassistant/loader.py", line 722, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/hass11/lib/python3.9/site-packages/homeassistant/loader.py", line 739, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/zonneplan_one/sensor.py", line 108, in <module>
    class ZonneplanSensor(CoordinatorEntity, SensorEntity):
  File "/home/homeassistant/.homeassistant/custom_components/zonneplan_one/sensor.py", line 203, in ZonneplanSensor
    def extra_state_attributes(self) -> dict[str, Any] | None:
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'
2022-12-05 11:05:54.103 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform zonneplan_one.sensor: Platform not found (Exception importing custom_components.zonneplan_one.sensor).
```

Can you help out here?

Thanx.

**Comment by fsaris** [comment]
What version of HA are you using?

**Comment by dajomas** [comment]
Currently using 2022.10.5

**Comment by dajomas** [comment]
Just tried to upgrade to 2022.11.5 but it produced the same error for version 0.0.14

**Comment by fsaris** [comment]
could you try to install the `main` version to see if my latest change fixes this issue for you?

https://github.com/fsaris/home-assistant-zonneplan-one#installing-mainbeta-version-using-hacs

**Comment by dajomas** [comment]
I am not using HACS (manually installing using GIT and symbolic links) so I'll fetch the latest version and try that one out.

I'll let you know the results
