### ISSUE TITLE
zonneplan one fails to start

### ISSUE THREAD

**Issue by sigio** [fsaris/home-assistant-zonneplan-one#71]
Logger: homeassistant.loader
Source: custom_components/zonneplan_one/coordinator.py:18
Integration: Zonneplan ONE ([documentation](https://github.com/fsaris/home-assistant-zonneplan-one), [issues](https://github.com/fsaris/home-assistant-zonneplan-one/issues))
First occurred: 14:21:58 (1 occurrences)
Last logged: 14:21:58

Unexpected exception importing component custom_components.zonneplan_one
Traceback (most recent call last):
  File "/home/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 725, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/zonneplan_one/__init__.py", line 13, in <module>
    from .coordinator import ZonneplanUpdateCoordinator
  File "/home/homeassistant/.homeassistant/custom_components/zonneplan_one/coordinator.py", line 18, in <module>
    def getGasPriceFromSummary(summary) -> int | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by sigio** [comment]
Looks like this uses a python 3.10 feature... while i'm on 3.9

**Comment by hmmbob** [comment]
3.9 is no longer supported by Home Assistant

**Comment by sigio** [comment]
Yeah, looks like i'm running 2023.1.7 ... but the fix is a simple one... So would be nice if this could be merged anyway

**Comment by sigio** [comment]
Especially since python 3.9 is the default in debian (and 3.8 is the default in centos/rhel/ubuntu 20.04)
